name: setup
description: Setup environment
inputs:
  exe_env:
    description: "Execution environment."
    required: false
    default: "docker"
  python-version:
    description: "python version."
    required: false
    default: "3.12"

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      if: ${{ inputs.exe_env == "poetry" }}
      with:
        python-version: ${{ inputs.python-version }}
    - name: setup poetry
      if: ${{ inputs.exe_env == "poetry" }}
      shell: bash
      run: |
        pip install poetry
        poetry install
        echo "$(poetry show -v|head -n1|awk '{print $3}')/bin" >> $GITHUB_PATH
    - name: pytest
      shell: bash
      run: pytest
    - name: hello
      shell: bash
      run: hello
