name: docker test

on:
  push:
  workflow_dispatch:
    inputs:
      exe_env:
        description: "Execution environment."
        type: choice
        required: false
        default: "docker"
        options:
          - "docker"
          - "poetry"
      use_buildx:
        description: "Use buildx or not to build docker image"
        type: boolean
        required: false
        default: true

env:
  USE_BUILDX: ${{ inputs.use_buildx || 'use_buildx' }}

jobs:
  docker-build:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.exe_env == 'docker') }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@3
      if: env.USE_BUILDX
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/test-image:${{ github.sha }}
  docker-test:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.exe_env == 'docker') }}
    needs: docker-build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/test-image:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
  poetry-test:
    if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.exe_env == 'poetry') }}
    runs-on: ubuntu-latest
    steps:
    - run: pipx install poetry
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: poetry install
    - run: poetry shell
    - uses: ./.github/actions/test
