name: docker test

on:
  push:
  workflow_dispatch:
    inputs:
      exe_env:
        description: "Execution environment."
        type: choice
        required: false
        default: "docker"
        options:
          - "docker"
          - "poetry"
      use_buildx:
        description: "Use buildx or not to build docker image"
        type: boolean
        required: false
        default: true
      image_name:
        description: "Docker image name"
        type: string
        required: false
        default: "test-image"

env:
  EXE_ENV: ${{ inputs.exe_env || 'docker' }}
  USE_BUILDX: ${{ inputs.use_buildx || 'use_buildx' }}
  IMAGE_NAME: ${{ inputs.image_name || 'test-image' }}

jobs:
  docker-build:
    if: env.EXE_ENV == 'docker'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@3
      if: env.USE_BUILDX
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  docker-test:
    if: env.EXE_ENV == 'docker'
    needs: docker-build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
  poetry-test:
    if: env.EXE_ENV == 'poetry'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '${{ inputs.python-version }}'
    - run: pipx install poetry
    - run: |
        poetry install
      with:
        python-version: 3.12
    - uses: ./.github/actions/test
